name: '${name}'
main: '${group}.${name}'

authors: [ badbones69, ryderbelserion ]

version: '${version}'
api-version: '${minecraft}'
description: '${description}'
website: '${website}'

folia-supported: true

softdepend:
  - CMI
  - DecentHolograms
  - FancyHolograms
  - PlaceholderAPI
  - MVdWPlaceholderAPI
  - Multiverse-Core
  - MultiWorld
  - MyWorlds
  - WorldEdit
  - WorldGuard
  - Oraxen
  - ItemsAdder
  - Nexo

permissions:
  envoy.bypass:
    default: op
  envoy.locations:
    default: false
  envoy.flare.use:
    default: false