name: '${name}'
main: '${group}.${name}'

authors: ${authors}

version: '${version}'
api-version: '${apiVersion}'
description: '${description}'
website: '${website}'

folia-supported: true

softdepend:
  - CMI
  - DecentHolograms
  - PlaceholderAPI
  - MVdWPlaceholderAPI
  - Multiverse-Core
  - MultiWorld
  - MyWorlds
  - WorldEdit
  - WorldGuard
  - Oraxen
  - ItemsAdder
  - Nexo

commands:
  crazyenvoys:
    description: "Manage your envoys however you want."
    aliases:
      - envoys
      - envoy

permissions:
  envoy.bypass:
    default: op
  envoy.locations:
    default: false
  envoy.stop:
    default: false
  envoy.start:
    default: false
  envoy.edit:
    default: false
  envoy.flare.use:
    default: false
  envoy.flare.give:
    default: false
  envoy.reload:
    default: false
  envoy.ignore:
    default: true
  envoy.drops:
    default: true
  envoy.help:
    default: true
  envoy.time:
    default: true